<?php
namespace Wambo\Core;

/*
 * define root directory for the project
 */
define('WAMBO_ROOT_DIR', dirname(getcwd() . '..'));

/*
 * load autoload file generated by composer
 */
$autoload_filename = WAMBO_ROOT_DIR . '/vendor/autoload.php';
if (!file_exists($autoload_filename)) {
    echo $autoload_filename . " was not found";
    exit(1);
}

require_once $autoload_filename;

$app = new App();
$app->run();