<?php
namespace Wambo\Core;

error_reporting(E_ALL);
ini_set('display_errors', 1);

// define root directory for the project
define('WAMBO_ROOT_DIR', dirname(getcwd() . '..'));

// load autoload file generated by composer
$autoload_filename = WAMBO_ROOT_DIR . '/vendor/autoload.php';
if (!file_exists($autoload_filename)) {
    echo $autoload_filename . " was not found";
    exit(1);
}

require_once $autoload_filename;

// load bootstrap DI configuration
$bootstrap_di_file = WAMBO_ROOT_DIR . '/app/src/bootstrap.php';
require_once $bootstrap_di_file;

$app = new App($container);
$app->run();